Array in List der ToDos zu einer Lsite umgewandelt und alle Tests angepasst
OGNylux/hwr-oop-project-gruppe6 pull request #30
Opened 2023-05-15 08:18 UTC by Tobree

Array LsitToDos in ListClass zu eines ArrayList umgewandelt 
Alle Verweise auf ListToDos auf Listen angepasst in ListClass und Main
MainTest und ListClassTest auf die Änderungen angepasst
ein Issue konnte auch gelöst werden

2023-05-16 10:59 UTC, OGNylux commented
Muss noch den BubbleUpBucket Algorithmus überarbeiten. Dann könnte man es mergen

2023-05-23 07:05 UTC, OGNylux approved these changes

2023-05-24 13:31 UTC, LukasKlockenhoff requested changes
Einiges nur Vorschläge aber vor allem die kleinen Sachen freuen Stefan bestimmt :)

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoItem.java
> +    //setter
Stört Stefan an der Stelle glaube ich.

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoItem.java
> +    //setter
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoItem.java
> +    //getter
Same here
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoItem.java
> +
Warum so viele NewLines ?

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoList.java
> +    } //needs test?
Bitte als TODO markieren.
```suggestion
    } //TODO: Needs test?
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoList.java
> +    //getter
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoList.java
> +        //remove any file extension if present
Stört Stefan evtl.
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/main/java/hwr/oop/ToDoList.java
> +    private List<ToDoItem> listToDos;
Refactor to Items
```suggestion
    private List<ToDoItem> items;
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/test/java/hwr/oop/ToDoItemTest.java
> +    //setter
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/test/java/hwr/oop/ToDoItemTest.java
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/test/java/hwr/oop/ToDoItemTest.java
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/test/java/hwr/oop/ToDoItemTest.java
> +    //getter
```suggestion
```

2023-05-24 13:31 UTC, LukasKlockenhoff commented on src/test/java/hwr/oop/ToDoListClassTest.java
> +public class ToDoListClassTest {
Nur ein Vorschlag:
```suggestion
public class ToDoListTest {
```

2023-05-24 13:31 UTC, LukasKlockenhoff requested changes
Einiges nur Vorschläge aber vor allem die kleinen Sachen freuen Stefan bestimmt :)

2023-05-30 07:11 UTC, Tobree reviewed
change requests wurden bearbeitet

2023-06-05 11:25 UTC, closed without merging